version: '3.2'

services:
  web:
    image: localhost:5000/sampleapp.web
    deploy:
      replicas: 3
    ports:
        - "8080:80"

  service1:
    image: localhost:5000/sampleapp.service1
    deploy:
      replicas: 3
    ports:
        - "80"

  service2:
    image: localhost:5000/sampleapp.service2
    deploy:
      replicas: 3
    ports:
        - "80"