version: '3'

services:
  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9000:80"

  service1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  service2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
