version: '3.2'

services:
  web:
    image: microservicessample.azurecr.io/sampleapp.web
    deploy:
      replicas: 1
    ports:
        - "80:80"

  service1:
    image: microservicessample.azurecr.io/sampleapp.service1
    deploy:
      replicas: 1
        
  service2:
    image: microservicessample.azurecr.io/sampleapp.service2
    deploy:
      replicas: 1